server:
  port: 12307
task:
  name:
    cron: cron_task_group_1
    simp: simp_task_group_1
job:
  execute:
    class-path: com.dmm.entry.MyJob
mybatis:
  type-aliases-package: com.dmm.entey
  mapper-locations: mapper/**Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      max-wait: 1000
logging:
  level:
    com:
      dmm: debug