server:
  port: 8888
  servlet:
    context-path: /rabbit

spring:
  rabbitmq:
    host: 47.111.2.18
    username: test
    password: test
    port: 5672
    publisher-confirms: true #消息确认机制，确认回调 确认消息是否到达 Broker 服务器
    publisher-returns: true #消息确认机制，返回回调 启动消息失败返回
    listener:
      simple:
        acknowledge-mode: manual #手动应答
        concurrency: 1 #最小消费者数量
        max-concurrency: 10 # 最大消费者数
        retry:
          enabled: true #是否支持重试
          max-attempts: 3 #重试最大次数
        prefetch: 3
    virtual-host: /test #虚拟主机