
# springboot 整合多数据源
spring:
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
    db2:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
  #多数据源时生效，需要手动配置
#mybatis:
#  mapper-locations: classpath:mapper/**Mapper.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: com.dmm.entry
logging:
  level:
    com.dmm: debug