  #端口
server:
  port: 9600
  #数据源的配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # 持久层配置
mybatis:
  mapper-locations: mapper/**Mapper.xml
  type-aliases-package: com.dmm.entry
  config-location: classpath:mybatis/mybatis-config.xml
  # 日志配置
logging:
  level:
    com.dmm.mapper: debug
  # 分页插件的配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql