spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db1:
      url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
    db2:
      url: jdbc:mysql://localhost:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 50000
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 100000
      max-create-task-count: 1
server:
  port: 9001
  servlet:
    context-path: /dmm
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.dmm.entry
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 4
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    jdbc-type-for-null: 'null'

logging:
  level:
    root: info