server:
  port: 12308

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#  jackson:
#    serialization: {"":"","":""}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true