server:
  port: 8889
mybatis:
  mapper-locations: mapper/**Mapper.xml
  type-aliases-package: com.dmm.entry
  configuration:
    default-statement-timeout: 1000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.dmm.mapper: debug
